sudo: required

language: c

matrix:
  include:
    - env: TEST_SUITE=testinstall GAPPKG=no
    - env: TEST_SUITE=testinstall GAPPKG=auto
    - env: TEST_SUITE=testinstall GAPPKG=all

    - env: TEST_SUITE=testbugfix GAPPKG=no
    - env: TEST_SUITE=testbugfix GAPPKG=auto
    - env: TEST_SUITE=testbugfix GAPPKG=all

    - env: TEST_SUITE=teststandard GAPPKG=no
    - env: TEST_SUITE=teststandard GAPPKG=auto
    - env: TEST_SUITE=teststandard GAPPKG=all

#   - env: TEST_SUITE=testextra GAPPKG=no
#   - env: TEST_SUITE=testextra GAPPKG=auto
#   - env: TEST_SUITE=testextra GAPPKG=all

    - env: TEST_SUITE=testpackagesload GAPPKG=single
    - env: TEST_SUITE=testpackagesload GAPPKG=singleonlyneeded
    - env: TEST_SUITE=testpackagesload GAPPKG=all
    - env: TEST_SUITE=testpackagesload GAPPKG=allreversed

services:
  - docker

before_install:
- docker pull gapsystem/gap-docker-stable-4.9

script:
    - docker version
    - docker run -v $PWD:/home/gap/travis/ gapsystem/gap-docker-stable-4.9 /bin/sh -c "TEST_SUITE=${TEST_SUITE} GAPPKG=${GAPPKG} TERM=dumb LANG=en_GB.UTF-8 /home/gap/travis/ci.sh"
